name:                monad-test
description:         ""
version:             0.1.0.0
license:             MIT
author:              "Keijo Kapp <keijo.kapp@gmail.com>"

dependencies:
- base >= 4.7 && < 5
- data-default-class
- mtl
- text
- ini
- x509
- tls
- warp
- warp-tls
- wai
- wai-extra
- wai-routes


executables:
  invoices-form:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-name-shadowing
